name: Generate Offline Package

on:
  workflow_dispatch:
    inputs:
      k8s_version:
        description: 'Select Kubernetes version to use'
        required: true
        default: 'v1.25.16'
      image_arch:
        description: 'Image arch'
        required: false
        default: 'amd64'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: eb-k8s/kubeaver/kubeaver_offline

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        cd offline_package
        pip install -r requirements.txt

    - name: Install package and tar to .tgz
      run: |
        cd offline_package
        python3 get_base.py --k8s_version=${{ github.event.inputs.k8s_version }} --image_arch=${{ github.event.inputs.image_arch }}
        
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }} 
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1      

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: offline_package
        file: offline_package/Dockerfile
        push: true
        pull: true
        platforms: linux/amd64
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:${{ github.event.inputs.k8s_version }}
        provenance: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Set image to Public
      run: |
        curl -X PATCH \
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        -H "Content-Type: application/json" \
        -d '{"visibility":"public"}' \
        "https://api.github.com/users/${{ github.repository_owner }}/packages/containers/${{ env.IMAGE_NAME }}/versions/${{ github.event.inputs.k8s_version }}"
